{"name": "test_cannot_create_two_identical_couriers", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_create_courier.TestCreateCourier object at 0x000001ADFD8D43B0>\ncreate_and_delete_courier = ({'firstName': 'nudmpceioe', 'login': 'reyjcapnkt', 'password': 'pqmmawuyvb'}, 442661)\n\n    def test_cannot_create_two_identical_couriers(self, create_and_delete_courier):\n        courier_data, _ = create_and_delete_courier\n    \n        response = requests.post(COURIER_URL, json=courier_data)\n        assert response.status_code == 409, (\n            f\"Повторное создание такого же курьера вернуло {response.status_code}, ожидали 409\")\n    \n        body = response.json()\n>       assert body.get(\"message\") == \"Этот логин уже используется\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntest_create_courier.py:31: AssertionError"}, "start": 1735226116003, "stop": 1735226116322, "uuid": "f800d54b-98c8-4327-a53c-d10daadf71c4", "historyId": "2651d7e59e7190665846ba8ea1c08001", "testCaseId": "2651d7e59e7190665846ba8ea1c08001", "fullName": "test_create_courier.TestCreateCourier#test_cannot_create_two_identical_couriers", "labels": [{"name": "tag", "value": "courier"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "NOTE-ENURMAMEDOV"}, {"name": "thread", "value": "17804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_courier"}]}