{"name": "test_create_courier_with_existing_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_create_courier.TestCreateCourier object at 0x000001ADFD8D5250>\ncreate_and_delete_courier = ({'firstName': 'valqstgakr', 'login': 'mhvqjxnwyd', 'password': 'pondymcooq'}, 442663)\n\n    def test_create_courier_with_existing_login(self, create_and_delete_courier):\n        courier_data, _ = create_and_delete_courier\n    \n        response = requests.post(COURIER_URL, json={\n            \"login\": courier_data[\"login\"],\n            \"password\": _generate_random_string(),\n            \"firstName\": _generate_random_string()})\n    \n        assert response.status_code == 409, (\n            f\"При создании курьера с занятым логином ожидали 409, а получили {response.status_code}\")\n    \n        body = response.json()\n>       assert body.get(\"message\") == \"Этот логин уже используется\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntest_create_courier.py:61: AssertionError"}, "start": 1735226119818, "stop": 1735226120133, "uuid": "e107b0be-6c61-40f0-8b0b-b946eda6b1a9", "historyId": "e93cee310989b7f9bd849f2bfaca5366", "testCaseId": "e93cee310989b7f9bd849f2bfaca5366", "fullName": "test_create_courier.TestCreateCourier#test_create_courier_with_existing_login", "labels": [{"name": "tag", "value": "courier"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "NOTE-ENURMAMEDOV"}, {"name": "thread", "value": "17804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_courier"}]}